import {existsSync} from 'node:fs';
import {mkdir, open, readdir, readFile, rename, stat, unlink, writeFile} from 'node:fs/promises';
import {dirname, isAbsolute, join, resolve} from 'node:path';
import {fileURLToPath} from 'node:url';
import {characterPreferencePath, userCharacterDirectory} from './paths.js';

export const defaultCharacter = 'copilot';
const idPattern = /^[a-z0-9][a-z0-9-]{0,15}$/;
const headerBytes = 256;
export const maxPackBytes = 16 * 1024 * 1024;
const pngSignature = Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a]);

export interface CharacterPackHeader {
  id: string;
  name: string;
  thumbnail: {offset: number; bytes: number} | null;
  // Largest blink patch in a base/patch pack; 0 for full-frame packs.
  maxPatchPixels: number;
}

export interface CharacterPackFile extends CharacterPackHeader {
  path: string;
  data: Buffer;
}

export interface CharacterEntry {
  id: string;
  name: string;
  builtIn: boolean;
  bytes: number;
  thumbnail: boolean;
}

// Built-in packs are generated by tools/character_pack.py inside the source checkout.
export function builtInCharacterDirectory(): string {
  if (process.env.AGENT_COMPANION_CHARACTERS) return process.env.AGENT_COMPANION_CHARACTERS;
  return join(dirname(fileURLToPath(import.meta.url)), '..', '..', '..', 'build', 'characters');
}

export function isCharacterName(value: string): boolean {
  return idPattern.test(value);
}

// Anything that doesn't look like a file path is a character name; names ignore case.
export function looksLikePackPath(value: string): boolean {
  return /[\\/]/.test(value) || value.toLowerCase().endsWith('.acpk');
}

// Names check the built-in packs first, then packs added from the settings page.
export function resolveCharacterPack(value: string, directory = builtInCharacterDirectory(),
                                     userDirectory = userCharacterDirectory()): string {
  if (!looksLikePackPath(value)) {
    const file = `${value.toLowerCase()}.acpk`;
    const builtIn = join(directory, file);
    const added = join(userDirectory, file);
    return !existsSync(builtIn) && existsSync(added) ? added : builtIn;
  }
  if (!isAbsolute(value)) throw new Error('Character pack paths must be absolute.');
  return value;
}

export function characterRequestValue(value: string, cwd: string): string {
  return looksLikePackPath(value) ? resolve(cwd, value) : value.toLowerCase();
}

// Validates the header fields the daemon relies on; the device validates the rest.
export function parseCharacterPackHeader(header: Buffer, fileBytes = header.length): CharacterPackHeader {
  if (header.length < headerBytes || header.toString('ascii', 0, 4) !== 'ACPK'
      || header.readUInt16LE(4) !== 1 || header.readUInt16LE(6) !== headerBytes)
    throw new Error('Not a version 1 character pack (.acpk).');
  if (header.readUInt32LE(8) !== fileBytes || fileBytes > maxPackBytes)
    throw new Error('Character pack size does not match its header.');
  const text = (offset: number, length: number) => {
    const raw = header.subarray(offset, offset + length);
    const end = raw.indexOf(0);
    return raw.toString('ascii', 0, end < 0 ? length : end);
  };
  const id = text(16, 16);
  const name = text(32, 24);
  if (!isCharacterName(id) || !name) throw new Error('Character pack id or name is invalid.');
  const offset = header.readUInt32LE(148);
  const bytes = header.readUInt32LE(152);
  const dataOffset = header.readUInt32LE(140);
  const thumbnail = bytes > 0 && offset >= headerBytes && offset + bytes <= dataOffset
    && dataOffset <= fileBytes ? {offset, bytes} : null;
  const maxPatchPixels = header.readUInt8(12) === 1 ? header.readUInt32LE(68) : 0;
  return {id, name, thumbnail, maxPatchPixels};
}

// Copilot's blink patches, the largest that firmware without adaptive patch RAM is known to run
// with Wi-Fi still working. That firmware keeps every blink buffer in internal RAM, so bigger
// patches leave Wi-Fi without memory to send packets.
export const legacyMaxPatchPixels = 7452;

export function packNeedsFirmwareUpdate(pack: Pick<CharacterPackHeader, 'maxPatchPixels'>,
                                        adaptivePatchRam: boolean): boolean {
  return pack.maxPatchPixels > legacyMaxPatchPixels && !adaptivePatchRam;
}

async function readPackHeader(path: string): Promise<CharacterPackHeader & {bytes: number}> {
  const file = await open(path, 'r');
  try {
    const {size} = await file.stat();
    const header = Buffer.alloc(headerBytes);
    await file.read(header, 0, headerBytes, 0);
    return {...parseCharacterPackHeader(header, size), bytes: size};
  } finally {
    await file.close();
  }
}

export async function readCharacterPack(value: string): Promise<CharacterPackFile> {
  const path = resolveCharacterPack(value);
  let data: Buffer;
  try {
    data = await readFile(path);
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code !== 'ENOENT') throw error;
    if (looksLikePackPath(value)) throw new Error(`Character pack not found: ${value}`);
    const available = await listBuiltInCharacters();
    throw new Error(available.length
      ? `Unknown character "${value}". Available: ${available.join(', ')}.`
      : 'No character packs are built yet. Run "npm run setup" from the repository root.');
  }
  return {...parseCharacterPackHeader(data), path, data};
}

async function packFiles(directory: string): Promise<string[]> {
  try {
    return (await readdir(directory)).filter(name => name.endsWith('.acpk')).sort();
  } catch {
    return [];
  }
}

export async function listCharacters(directory = builtInCharacterDirectory(),
                                     userDirectory = userCharacterDirectory()): Promise<CharacterEntry[]> {
  const entries = new Map<string, CharacterEntry>();
  for (const [folder, builtIn] of [[userDirectory, false], [directory, true]] as const) {
    for (const file of await packFiles(folder)) {
      try {
        const header = await readPackHeader(join(folder, file));
        if (`${header.id}.acpk` !== file) continue;
        entries.set(header.id, {id: header.id, name: header.name, builtIn, bytes: header.bytes,
                                thumbnail: header.thumbnail !== null});
      } catch {
        // Unreadable or foreign files are not offered.
      }
    }
  }
  return [...entries.values()].sort((a, b) => a.name.localeCompare(b.name));
}

export async function readCharacterThumbnail(id: string): Promise<Buffer | null> {
  if (!isCharacterName(id)) return null;
  const path = resolveCharacterPack(id);
  try {
    const header = await readPackHeader(path);
    if (!header.thumbnail) return null;
    const file = await open(path, 'r');
    try {
      const image = Buffer.alloc(header.thumbnail.bytes);
      await file.read(image, 0, image.length, header.thumbnail.offset);
      return image.subarray(0, pngSignature.length).equals(pngSignature) ? image : null;
    } finally {
      await file.close();
    }
  } catch {
    return null;
  }
}

// Stores an uploaded pack beside the daemon's data so it can be installed by name.
export async function addCharacterPack(data: Buffer, directory = builtInCharacterDirectory(),
                                       userDirectory = userCharacterDirectory()): Promise<CharacterEntry> {
  const header = parseCharacterPackHeader(data);
  if (existsSync(join(directory, `${header.id}.acpk`)))
    throw new Error(`A built-in character already uses the id "${header.id}".`);
  await mkdir(userDirectory, {recursive: true, mode: 0o700});
  const path = join(userDirectory, `${header.id}.acpk`);
  const temporary = `${path}.tmp`;
  await writeFile(temporary, data, {mode: 0o600});
  await rename(temporary, path);
  return {id: header.id, name: header.name, builtIn: false, bytes: data.length,
          thumbnail: header.thumbnail !== null};
}

export async function removeCharacterPack(id: string, userDirectory = userCharacterDirectory()): Promise<void> {
  if (!isCharacterName(id)) throw new Error('Invalid character id.');
  const path = join(userDirectory, `${id}.acpk`);
  try {
    await stat(path);
  } catch {
    throw new Error('Only characters you added can be removed.');
  }
  await unlink(path);
}

export async function listBuiltInCharacters(directory = builtInCharacterDirectory()): Promise<string[]> {
  return (await listCharacters(directory)).map(entry => entry.id).sort();
}

export async function loadCharacterPreference(): Promise<string> {
  try {
    const value = JSON.parse(await readFile(characterPreferencePath(), 'utf8')) as {character?: unknown};
    if (typeof value.character === 'string'
        && (isCharacterName(value.character) || isAbsolute(value.character)))
      return value.character;
  } catch {
    // A missing or unreadable preference falls back to the default character.
  }
  return defaultCharacter;
}

export async function saveCharacterPreference(character: string): Promise<void> {
  const path = characterPreferencePath();
  await mkdir(dirname(path), {recursive: true, mode: 0o700});
  const temporary = `${path}.tmp`;
  await writeFile(temporary, `${JSON.stringify({character}, null, 2)}\n`, {mode: 0o600});
  await rename(temporary, path);
}
